#!/bin/bash

set -e
set -o pipefail

cd "$(dirname "$0")"/..
ROOT=$(pwd)

if ! git diff-index --quiet HEAD --; then
    echo "Changes in local directory, commit or clear" >&2
    exit 1
fi

VERSION="$(grep __VERSION__ "$ROOT/{MODULE}/__init__.py" | sed -e "s/.* = '//" -e "s/'$//")"
SHA=$(git rev-parse HEAD)
python setup.py sdist
TARBALL="dist/{MODULE_DASHED}-$SHA.tar.gz"
mv dist/{MODULE_DASHED}-$VERSION.tar.gz "$TARBALL"

echo "Created $TARBALL"
