#!/bin/bash

set -e

ROOT=$(dirname $(dirname $0))

# find all the modules in our template setup.py, this isn't a perfect solution,
# but it works well enough, until it doesn't...
MODULES="$(grep "    '.*',$" setup.py | sed -E "s/ +'/'/;")"

# Create temporary directory
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

# Write setup.py to temporary directory
cat << EOF > "$TEMP_DIR/setup.py"
from setuptools import setup

setup(
    name='your-package-name',
    version='0.0.1',
    install_requires=[
$MODULES
    ],
    python_requires='>=3.10',
)
EOF

# Run proviso on the temporary directory
proviso --directory="$TEMP_DIR" --header="# TODO: Run ./script/update-requirements once setup.py is complete" "$@"

mv "${TEMP_DIR}/requirements.txt" "${ROOT}/requirements.txt"