#!/bin/bash

# ([[ `git status --porcelain` ]] && echo "local changes" && exit 1 || exit 0) && (test $(git rev-parse --abbrev-ref HEAD) != "main" && echo "on branch" && exit 1 || exit 0) && ~/octodns/octodns-template/script/look-for-changes 2>&1 | tee /tmp/changes.patch
#
# ~/octodns/octodns-template/script/look-for-changes 2>&1 | tee /tmp/changes.patch
#
# ./script/format && git checkout -b general-updates && git add -p && git commit -m "Updates to latest template" && ./script/update-requirements && git add -p && git commit -m "Update requirements files" && git pob
#
# hub pull-request --file /tmp/body.txt -b main -h general-updates -a ross

set -e
set -o pipefail

MDIR=$(pwd)
cd "$(dirname "$0")/.."
ROOT=$(pwd)

echo "## paths #######################################################################"
echo "root: $ROOT"
echo "moduledir: $MDIR"
TDIR=$(mktemp -d)
echo "tempdir: $TDIR"

echo "## template vars ###############################################################"
MODULE=$(basename "$MDIR" | sed 's/-/_/')
echo "module: $MODULE"
PROVIDER=$(grep --no-filename -r '^class .*\(Provider\|Source\)(' "$MDIR/$MODULE/" | sed -e 's/class //' -e 's/(.*//' | head -n 1)
echo "provider: $PROVIDER"
NAME=$(head -n 1 $MDIR/README.md | sed -e 's/## //' -e 's/ provider.*//')
echo "name: $NAME"
LINK=$(grep 'provider that targets' $MDIR/README.md | sed -e 's/.*targets .*](//' -e 's/)\.$//' || echo "NoT-FoUnD")
echo "link: $LINK"
AUTHOR=$(grep 'author=' "$MDIR/setup.py" | sed -e "s/.*author='//" -e "s/',//")
echo "author: $AUTHOR"
AUTHOR_EMAIL=$(grep 'author_email=' "$MDIR/setup.py" | sed -e "s/.*author_email='//" -e "s/',//")
echo "author_email: $AUTHOR_EMAIL"

cd $TDIR

$ROOT/script/template \
    --module "$MODULE" \
    --provider "$PROVIDER" \
    --name "$NAME" \
    --link "$LINK" \
    --author "$AUTHOR" \
    --author-email "$AUTHOR_EMAIL"

FILES=$(
    find -type f |
        grep -v "$MODULE" |
        grep -v tests |
        grep -v 'README.md' |
        grep -v 'CHANGELOG.md' |
        grep -v 'requirements' |
        sed -E 's#\.\/##'
)
for file in $FILES; do
    DIFF=$(diff -u "${MDIR}/${file}" "$file" || true)
    # if there are subtractions or if there are additions that aren't exports
    if echo "$DIFF" | grep -q '^-' || echo "$DIFF" | grep -q '^+' | grep -qv '^+export '; then
        echo "$DIFF"

        # Ask if user wants to patch the file
        read -p "Would you like to try and patch ${file}? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            if echo "$DIFF" | patch -p0 "${MDIR}/${file}"; then
                echo "Successfully patched ${file}"
            else
                echo "Failed to patch ${file}"
            fi
        fi

        # Ask if user wants to edit the file
        read -p "Would you like to edit ${file}? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            ${EDITOR:-vi} "${MDIR}/${file}"
        fi
    fi
done
